AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Cloud Assignment - Backend with SAM

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: customer_ids

Resources:
  ### DynamoDB
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: customer_ids
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ### API
  CustomerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ### SNS
  UserCreatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: user-created-alerts
      Subscription:
        - Protocol: email
          Endpoint: r0ginskiial@gmail.com

  ### Lambdas
  PutCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/put_customer_id/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: customer_ids
        - SNSPublishMessagePolicy:
            TopicName: user-created-alerts
      Environment:
        Variables:
          TABLE_NAME: customer_ids
          SNS_TOPIC_ARN: !Ref UserCreatedTopic
      Events:
        PutCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref CustomerApi
            Path: /customer
            Method: post
            Auth:
              ApiKeyRequired: true

  GetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/get_customer_id/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: customer_ids
      Events:
        GetCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref CustomerApi
            Path: /customer/{id}
            Method: get
            Auth:
              ApiKeyRequired: true

  DeleteCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/delete_customer_id/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: customer_ids
      Events:
        DeleteCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref CustomerApi
            Path: /customer/{id}
            Method: delete
            Auth:
              ApiKeyRequired: true

  StreamProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/stream_processor/
      Handler: app.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref CustomerStateMachine
      Environment:
        Variables:
          CUSTOMER_STATE_MACHINE_ARN: !Ref CustomerStateMachine
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt CustomerTable.StreamArn
            StartingPosition: TRIM_HORIZON

  ProcessCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/process_customer/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: customer_ids
      Environment:
        Variables:
          PROCESSED_CUSTOMERS_TABLE: !Ref CustomerTable

  ### Step Function
  CustomerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: CustomerWorkflow
      Definition:
        Comment: "Workflow запускается при добавлении нового customer"
        StartAt: ProcessCustomer
        States:
          ProcessCustomer:
            Type: Task
            Resource: !GetAtt ProcessCustomerFunction.Arn
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessCustomerFunction

  ### API Gateway Usage Plan + Key
  CustomerUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: CustomerPlan
      ApiStages:
        - ApiId: !Ref CustomerApi
          Stage: !Ref CustomerApi.Stage  # Ссылка на Stage, созданный SAM автоматически
      Throttle:
        RateLimit: 10
        BurstLimit: 5
      Quota:
        Limit: 1000
        Period: MONTH

  CustomerApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: CustomerApiKey
      Enabled: true

  CustomerUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref CustomerApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref CustomerUsagePlan

  ### EventBridge Rule
  EventBridgeInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowStartExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: "*"

  CustomerEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.dynamodb"
        detail-type:
          - "AWS API Call via CloudTrail"
      Targets:
        - Arn: !Ref CustomerStateMachine
          Id: "CustomerWorkflowTarget"
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn

Outputs:
  CustomerApiBaseUrl:
    Description: "Base URL for Customer API"
    Value: !Sub "https://${CustomerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CustomerTableName:
    Description: "DynamoDB table name"
    Value: !Ref CustomerTable
  CustomerApiKeyValue:
    Description: "API Key for Customer API"
    Value: !Ref CustomerApiKey
  CustomerStateMachineArn:
    Description: "ARN of Customer Step Function"
    Value: !Ref CustomerStateMachine
  UserCreatedTopicArn:
    Description: "SNS Topic ARN for new user alerts"
    Value: !Ref UserCreatedTopic
